name: build-and-test

on:
    workflow_dispatch:

jobs:
  build_and_test
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: setup
        uses: actions/setup-python@v3
        with:
            python-version: 3.11

        - name: install
        run: |
            python3 -m pip3 install --upgrade pip3
            pip install pytest

        - name: test
        run: |
          pytest -v /tests